# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 334062e3c896a301c228f3657545d4b6a19d829767a14ed93bd74e2c3d5b14008369b1a4a6e04194f0f58b7d0d96c0fb256f258aaad0f22d70622e232db59ab8

test:
  secret_key_base: b2e8b208fac3aa9f932c3b7d38d112b24b2fda8a8f121d4354ba276169384b9316229182f114a08dacadf33a75d3bf9393484ac8bafe6e1fabfb79c2c2038933

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
